{ config, pkgs, inputs, ... }:

{
  imports = [
    ./hardware-configuration.nix   # generated by nixos-generate-config
    ./modules/nvidia.nix
    ./modules/keyd.nix
    ./modules/hyprland.nix
  ];

  # ── Bootloader ────────────────────────────────────────────────────────────
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  # Show the boot menu for 3 seconds so you can pick Windows
  boot.loader.systemd-boot.configurationLimit = 10;
  boot.loader.timeout = 3;

  # ── Kernel ────────────────────────────────────────────────────────────────
  boot.kernelPackages = pkgs.linuxPackages_latest;

  # ── Networking ────────────────────────────────────────────────────────────
  networking.hostName = "lockie-nixos";
  networking.networkmanager.enable = true;

  # ── Locale & time ─────────────────────────────────────────────────────────
  time.timeZone = "America/Chicago";   # Aurora, IL
  i18n.defaultLocale = "en_US.UTF-8";

  # ── Nix settings ──────────────────────────────────────────────────────────
  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    auto-optimise-store = true;
  };
  # Keep the last 5 generations, GC anything older than 14 days
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 14d";
  };

  # ── nix-ld (required for JetBrains + other pre-built binaries) ────────────
  programs.nix-ld.enable = true;
  programs.nix-ld.libraries = with pkgs; [
    stdenv.cc.cc.lib
    zlib
    glib
    libGL
    openssl
    xorg.libX11
    xorg.libXext
    xorg.libXrender
    xorg.libXtst
    xorg.libXi
    xorg.libxcb
    fontconfig
    freetype
  ];

  # ── User ──────────────────────────────────────────────────────────────────
  users.users.lockie = {
    isNormalUser = true;
    description = "lockie";
    extraGroups = [ "networkmanager" "wheel" "video" "input" "audio" ];
    shell = pkgs.bash;
  };

  # ── Base system packages ───────────────────────────────────────────────────
  # Keep this lean — most packages live in home.nix via Home Manager
  environment.systemPackages = with pkgs; [
    git
    curl
    wget
    vim          # emergency editor before Neovim is set up
    pciutils
    usbutils
    lshw
  ];

  # ── Audio (PipeWire) ───────────────────────────────────────────────────────
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # ── Fonts (base — more added in Phase 6) ──────────────────────────────────
  fonts.packages = with pkgs; [
    noto-fonts
    noto-fonts-emoji
  ];

  # ── Polkit (required by Hyprland) ─────────────────────────────────────────
  security.polkit.enable = true;

  # ── Flatpak (for Discord, Spotify) ────────────────────────────────────────
  services.flatpak.enable = true;
  xdg.portal = {
    enable = true;
    extraPortals = [ pkgs.xdg-desktop-portal-gtk ];
  };

  system.stateVersion = "24.11";
}
