name = "spotatui-party"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[durable_objects.bindings]]
name = "PARTY_ROOM"
class_name = "PartyRoom"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "46aa61cd5be0433faa3d4b85be1380fb"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["PartyRoom"]
